# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rater}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.date = %q{2011-04-18}
  s.extra_rdoc_files = [
    "README.mdown"
  ]
  s.files = [
    "app/controllers/rater/ratings_controller.rb",
    "app/models/rater/rating.rb",
    "config/routes.rb",
    "lib/acts_as_rated/base.rb",
    "lib/application_helper.rb",
    "lib/engine.rb",
    "lib/rails/generators/rater_install_generator.rb",
    "lib/rails/generators/templates/migration.rb",
    "lib/rater.rb"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ratings Engine for Rails 3}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

